name: Docker

on:
  schedule:
    - cron: '35 4 * * *'
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: dipakrasal2009/docker-image_with_github-action  # Update this


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          # password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  install:
     runs-on: ubuntu-latest
     needs: build
     steps:
         - name: print the message
           run: |
             echo "docker installed successfully...................."
             sleep 5
           
  status:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - name: check the status iof docker
          run: sleep 3
  
   
  run:
    runs-on: ubuntu-latest
    needs: status
    steps:
        - name: sleept for 10 sec
          run: sleep 5

  testing:
    runs-on: ubuntu-latest
    needs: install
    steps:
        - name: check the status iof docker
          run: sleep 2

  status:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - name: check the status
          run: sleep 15

